# Generated by Django 4.2.1 on 2023-05-29 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingBid', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='watchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wlpeopple', to='auctions.auctionlisting')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcomments', to='auctions.auctionlisting')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pplcomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidVal', models.IntegerField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersbids', to=settings.AUTH_USER_MODEL)),
                ('listingOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auctions.auctionlisting')),
            ],
        ),
    ]
