# Generated by Django 4.2.1 on 2023-05-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='imgLink',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
