# Generated by Django 4.2.1 on 2023-05-30 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='isClosed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leaderslistings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
