# Generated by Django 4.2.1 on 2023-05-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_isclosed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='leader',
        ),
    ]
