# Generated by Django 4.2.1 on 2023-05-30 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderslistings', to=settings.AUTH_USER_MODEL),
        ),
    ]
