# Generated by Django 4.2.1 on 2023-05-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionlisting_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='isClosed',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='leader',
        ),
    ]
